#!/usr/bin/env python3
"""Generate SQL to fix Book1 color-coded candidate stages (green=Selected, blue=Hired)."""

from __future__ import annotations

import json
import re
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[2]
XLSX = ROOT / "Book1.xlsx"
OUT = ROOT / "backend" / "migrations" / "fix_book1_candidate_stages.sql"

GREEN = "#92D050"
BLUE = "#9BC2E6"


def sql_escape(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def get_cell_color(cell) -> str | None:
    fill = cell.fill
    if not fill or not fill.fgColor:
        return None
    rgb = fill.fgColor.rgb
    if not rgb or str(rgb) in ("00000000", "FFFFFFFF", "None"):
        return None
    s = str(rgb)
    if len(s) == 8:
        return "#" + s[2:].upper()
    return "#" + s.upper()


def normalize_name(name: str) -> str:
    return re.sub(r"\s+", " ", name.strip().lower())


def main() -> None:
    wb = openpyxl.load_workbook(XLSX)
    ws = wb.active

    raw_rows = []
    for r in range(2, ws.max_row + 1):
        name = ws.cell(r, 2).value
        if not name or not str(name).strip():
            continue

        colors = [get_cell_color(ws.cell(r, c)) for c in range(1, 7)]
        pos = str(ws.cell(r, 3).value or "").strip()
        remarks = str(ws.cell(r, 5).value or "").strip()
        status = str(ws.cell(r, 4).value or "").strip()

        if BLUE in colors:
            stage, main_stage = "Hired", "hired"
        elif GREEN in colors:
            stage, main_stage = "Selected", "selected"
        else:
            continue

        score = (10 if pos else 0) + (5 if remarks else 0) + (3 if status else 0) + 5
        raw_rows.append(
            {
                "row": r,
                "name": str(name).strip(),
                "name_key": normalize_name(str(name)),
                "stage": stage,
                "main_stage": main_stage,
                "score": score,
            }
        )

    best_by_name: dict[str, dict] = {}
    for row in raw_rows:
        key = row["name_key"]
        existing = best_by_name.get(key)
        if existing is None or row["score"] > existing["score"] or (
            row["score"] == existing["score"] and row["row"] > existing["row"]
        ):
            best_by_name[key] = row

    rows = sorted(best_by_name.values(), key=lambda x: (x["stage"], x["name"].lower()))
    hired = [r for r in rows if r["stage"] == "Hired"]
    selected = [r for r in rows if r["stage"] == "Selected"]

    lines: list[str] = []
    lines.append("-- ============================================================")
    lines.append("-- Fix Book1.xlsx color-coded candidate stages on kanban board")
    lines.append("-- Green row (#92D050) -> Selected column (main_stage = selected)")
    lines.append("-- Blue row  (#9BC2E6) -> Hired column    (main_stage = hired)")
    lines.append("-- Matches candidates uploaded by Khushi from Book1.xlsx import")
    lines.append("-- Generated by: backend/scripts/generate_book1_stage_fix_sql.py")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("SET @khushi_user_id = (SELECT id FROM users WHERE username = 'khushi' LIMIT 1);")
    lines.append("")
    lines.append("SELECT IF(@khushi_user_id IS NULL,")
    lines.append("  'ERROR: Khushi user not found',")
    lines.append("  CONCAT('Fixing stages for uploader id ', @khushi_user_id)) AS status;")
    lines.append("")
    lines.append("START TRANSACTION;")
    lines.append("")

    def emit_bulk_update(label: str, stage: str, main_stage: str, names: list[str]) -> None:
        if not names:
            return
        lines.append(f"-- {label}: {len(names)} candidates")
        # Chunk IN lists to stay under max_allowed_packet
        chunk_size = 40
        for i in range(0, len(names), chunk_size):
            chunk = names[i : i + chunk_size]
            in_list = ", ".join(sql_escape(n) for n in chunk)
            lines.append(
                "UPDATE candidates "
                f"SET stage = {sql_escape(stage)}, "
                f"main_stage = {sql_escape(main_stage)}, "
                "sub_stage = NULL, "
                "stage_updated_at = NOW(), "
                "updated_at = NOW() "
                "WHERE uploaded_by = @khushi_user_id "
                f"AND name IN ({in_list});"
            )
        lines.append("")

    emit_bulk_update("Hired (blue rows)", "Hired", "hired", [r["name"] for r in hired])
    emit_bulk_update("Selected / Shortlisted (green rows)", "Selected", "selected", [r["name"] for r in selected])

    lines.append("COMMIT;")
    lines.append("")
    lines.append("-- Verification")
    lines.append("SELECT stage, main_stage, COUNT(*) AS cnt")
    lines.append("FROM candidates")
    lines.append("WHERE uploaded_by = @khushi_user_id")
    lines.append("  AND stage IN ('Selected', 'Hired')")
    lines.append("GROUP BY stage, main_stage")
    lines.append("ORDER BY stage;")
    lines.append("")
    lines.append(f"-- Expected: Selected/selected = {len(selected)}, Hired/hired = {len(hired)}")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"hired": len(hired), "selected": len(selected), "output": str(OUT)}, indent=2))


if __name__ == "__main__":
    main()
