CREATE TABLE IF NOT EXISTS candidate_assignments (
  id                  INT AUTO_INCREMENT PRIMARY KEY,
  candidate_id        VARCHAR(36) NOT NULL,
  assignment_id       INT NOT NULL,
  assigned_by         INT NOT NULL,
  token               VARCHAR(64) NOT NULL UNIQUE,
  submission_link     VARCHAR(512) NOT NULL,
  status              ENUM('Assigned','Submitted','Overdue','Reviewed') DEFAULT 'Assigned',
  deadline            DATETIME NOT NULL,
  expiry_at           DATETIME NOT NULL,
  single_use          TINYINT(1) DEFAULT 1,
  auto_advance        TINYINT(1) DEFAULT 0,
  email_body          TEXT,
  custom_slug         VARCHAR(200),
  notify_deadline     TINYINT(1) DEFAULT 1,
  notify_expiry       TINYINT(1) DEFAULT 1,
  notify_submission   TINYINT(1) DEFAULT 1,
  deadline_notified   TINYINT(1) DEFAULT 0,
  expiry_notified     TINYINT(1) DEFAULT 0,
  submitted_at        DATETIME,
  submission_notes    TEXT,
  email_status        ENUM('Pending','Sent','Failed') DEFAULT 'Pending',
  email_attempts      INT DEFAULT 0,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_candidate_id (candidate_id),
  KEY idx_assignment_id (assignment_id),
  KEY idx_token (token),
  KEY idx_status (status),
  KEY idx_deadline (deadline),
  KEY idx_expiry_at (expiry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
