-- ============================================================
-- Fix Book1.xlsx color-coded candidate stages on kanban board
-- Green row (#92D050) -> Selected column (main_stage = selected)
-- Blue row  (#9BC2E6) -> Hired column    (main_stage = hired)
-- Matches candidates uploaded by Khushi from Book1.xlsx import
-- Generated by: backend/scripts/generate_book1_stage_fix_sql.py
-- ============================================================

SET @khushi_user_id = (SELECT id FROM users WHERE username = 'khushi' LIMIT 1);

SELECT IF(@khushi_user_id IS NULL,
  'ERROR: Khushi user not found',
  CONCAT('Fixing stages for uploader id ', @khushi_user_id)) AS status;

START TRANSACTION;

-- Hired (blue rows): 20 candidates
UPDATE candidates SET stage = 'Hired', main_stage = 'hired', sub_stage = NULL, stage_updated_at = NOW(), updated_at = NOW() WHERE uploaded_by = @khushi_user_id AND name IN ('Akshay Jethani', 'Atharva Sheelwant', 'Bhoomika Patil', 'Ganesh Bobade', 'Gaurav More', 'Jayshankar Tripathi', 'kaustubh Pawar', 'Khushi Jat', 'Kushal Shete', 'Namrata', 'Radhika Jaju', 'Ruchita Thorat', 'Rudrakshi Sathe', 'Shital Vijapure', 'Siddhesh Methe', 'Sujay Jirapure', 'Surbhi Ushek', 'Surbhi Ushekwar', 'Tanishka tondwalkar', 'Yash');

-- Selected / Shortlisted (green rows): 38 candidates
UPDATE candidates SET stage = 'Selected', main_stage = 'selected', sub_stage = NULL, stage_updated_at = NOW(), updated_at = NOW() WHERE uploaded_by = @khushi_user_id AND name IN ('Abhishek Morkhade', 'Adarsh gawande', 'Adrija Roy', 'Akanksha', 'Akanksha Deo', 'Aniket Patil', 'Apurva Pawar', 'Bhagyashree Sonone', 'Charushi Mishra', 'Fatima Kirosha', 'Harshal Bodade', 'Kaustubh Khandagale', 'Manya Vashisth', 'Maria Gomes', 'Megha Vyas', 'Neha Verma', 'Pawan Tekadi', 'pranay langhe', 'Purobi Sen', 'Rinchen Balvally', 'Riya Potipelliwar', 'Rohit Patel', 'Sadiyya Sarkar', 'Sagar Kumbhar', 'Sakshi Madavi', 'Samiksha', 'Sandesh Dande', 'Sanjana Navale', 'Shipra Pandey', 'Shravani Patil', 'Shubham Jadhav', 'Supriya Shinde', 'Swapnil Srivastava', 'Swati Burute', 'Tanisha Vatsa', 'Ummeyusra Khateeb', 'Vidhan Badkelwar', 'Vivek Deshmukh');

COMMIT;

-- Verification
SELECT stage, main_stage, COUNT(*) AS cnt
FROM candidates
WHERE uploaded_by = @khushi_user_id
  AND stage IN ('Selected', 'Hired')
GROUP BY stage, main_stage
ORDER BY stage;

-- Expected: Selected/selected = 38, Hired/hired = 20
